#Pytorch Notebook
--- 
## Goal
Learn freaking pytorch so I can get cracked at quantum and start learning deep learning ML concepts. 

## Basic Notes 

- Tenor Library that uses Numpy to help accelerate computation in GPUs and CPUs
- Its differentiation engine allows for automatic calculations for many different Tensor operations. This helps w/ model optimization. 
- Has hecka pre-made building blocks that help users and devs lock in faster

### Machine learning

- LLMS are a type of deep learning neural network
- ML is a subsection of AI that focuses on optimizing computer learning algorithms 
- MLs make predictions and desions based off the data they learn w/o being explicity programmed to do the specific task. 
- They get better overtime with the more feedback they get 

### Deep learning

- Deep learning is a subcategory of machine learning that focuses on the traing and applying deep neural networks. 
- neural networks are supposed to reflect how the human brain works with many differnt artificial neurons and nodes that allow modeling of nonlinear relationships in data.
- deep learning is good at handling unstructured data like images, audio, or text, so its well suited for LLMs
- Supervised learning is when you train a model using data sets with examples and labels --> once trained models can predict the labels of new data. 









In [ ]:
import torch

torch.__version__


'2.12.0+cpu'

In [2]:
torch.cuda.is_available()

False

## Understanding Tensors
---
Tensors are a math concept that generalize vectors and matrices to potentially reach higher dimentions 

scalar = rank 0 tensor
vector = rank 1 tensor
matrix = rank 2 tensor 

- tensors act as data container on a computational basis. They hold multidemtional data and each demention represent another feature. Tensor libraries like PyTorch work as array libraries. 
-  PyTorch adopts most of the NumPy array API and syntax for its tensor operations. 


In [3]:
# ceate a 0D tenspr from a Python int
tensor0d = torch.tensor(7)
tensor0d

tensor(7)

In [5]:
# create a 1D tensor from a python list

tensor1d = torch.tensor([6,7,6,7])
tensor1d

tensor([6, 7, 6, 7])

In [6]:
# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [7]:
# Create a 3D tensor '

tensor3d = torch.tensor([[[1,2],
                          [3,4]],
                          [[5,6],
                           [7,8]]])
tensor3d

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

## Tensor Data Types 

above we made tensors using python integers . In this case we have a default 64-bit data type. Data type can be found with the .dtype attribute of an integer. 

In [3]:
import torch
tensor1d = torch.tensor([6,7,6,7])
tensor1d.dtype


torch.int64

if we make tensors using python floats, PyTorch creats tensors with a 32-bit data type automatically

In [ ]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
floatvec.dtype

# uses a 32 bit float in order to offer precision while also taking up less memory than a 64 bit float

torch.float32

u can change the data type using the .to method

In [5]:
floatvec = tensor1d.to(torch.float32)
floatvec.dtype

torch.float32

## Essential Tensor Operations
---
There are many operations and commands in Pytorch, so learning all of them is uneccessary for me rn. 


In [6]:
tensor2d = torch.tensor([[1,2,3],[4,5,6]]) #torch.tensor() creates new tensors from data (like a list or nested list)
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [7]:
# the .shape attribute returns a tuple of the dimensions of a tensor
tensor2d.shape

torch.Size([2, 3])

In [ ]:
# .reshape() and .view() allow us to reshape an input tensor to a defined shape
reshaped_tensor2d = tensor2d.reshape(3,2)
reshaped_tensor2d

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [11]:
# .T transposes a tensor (switches the dimensions)
reshaped_tensor2d.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [12]:
# .matmul() performs matrix multiplication between two tensors
tensor1 = torch.tensor([[1,2],
                        [3,4]])
tensor2 = torch.tensor([[5,6],
                        [7,8]])
torch.matmul(tensor1, tensor2)

tensor([[19, 22],
        [43, 50]])

In [ ]:
#you can also use an alt way
tensor1 @ tensor2
#and another
tensor1.matmul(tensor2)

tensor([[19, 22],
        [43, 50]])

## Seeing models as computation graphs
--- 
- we covered Pytorch's tensor library but now we need to look into pytorch's automatic differentiation system 
- the module base class makes it easier to train models. 
- it allows us to encapsulate layers and operations and keep track of the model’s parameters

- computational graphs let us vizualize math concepts, in deep learning a computation graphn lets us veiw the math needed to output a neural network
- we need the calculations to compute the gradients for backpropogation which is the primary training algorithm for neural networks

In [17]:
import torch.nn.functional as F

y = torch.tensor([1.0]) # true label
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # weight
b = torch.tensor([0.0]) # bias

z = x1 * w1 + b # net input 
a = torch.sigmoid(z) # activation function
loss = F.binary_cross_entropy(a, y) # calculate the loss
print(loss)


tensor(0.0852)


The point of this logistic regression classifier isnt to implement it but more so help us understand how we can think of a sequance of computations as a computation graph

- pytorch builds compuation graphs in the background and we can use this to calculate the gradient of a loss function that follows the weight and bias models to train the model. 

## Automatic differentiation 


In [ ]:
#ijcorjvowaecjiweoiv
