#Pytorch Notebook
--- 
## Goal
Learn freaking pytorch so I can get cracked at quantum and start learning deep learning ML concepts. 

## Basic Notes 

- Tenor Library that uses Numpy to help accelerate computation in GPUs and CPUs
- Its differentiation engine allows for automatic calculations for many different Tensor operations. This helps w/ model optimization. 
- Has hecka pre-made building blocks that help users and devs lock in faster

### Machine learning

- LLMS are a type of deep learning neural network
- ML is a subsection of AI that focuses on optimizing computer learning algorithms 
- MLs make predictions and desions based off the data they learn w/o being explicity programmed to do the specific task. 
- They get better overtime with the more feedback they get 

### Deep learning

- Deep learning is a subcategory of machine learning that focuses on the traing and applying deep neural networks. 
- neural networks are supposed to reflect how the human brain works with many differnt artificial neurons and nodes that allow modeling of nonlinear relationships in data.
- deep learning is good at handling unstructured data like images, audio, or text, so its well suited for LLMs
- Supervised learning is when you train a model using data sets with examples and labels --> once trained models can predict the labels of new data. 









In [82]:
import torch

torch.__version__


'2.12.0+cpu'

In [83]:
torch.cuda.is_available()

False

## Understanding Tensors
---
Tensors are a math concept that generalize vectors and matrices to potentially reach higher dimentions 

scalar = rank 0 tensor
vector = rank 1 tensor
matrix = rank 2 tensor 

- tensors act as data container on a computational basis. They hold multidemtional data and each demention represent another feature. Tensor libraries like PyTorch work as array libraries. 
-  PyTorch adopts most of the NumPy array API and syntax for its tensor operations. 


In [84]:
# ceate a 0D tenspr from a Python int
tensor0d = torch.tensor(7)
tensor0d

tensor(7)

In [85]:
# create a 1D tensor from a python list

tensor1d = torch.tensor([6,7,6,7])
tensor1d

tensor([6, 7, 6, 7])

In [86]:
# create a 2D tensor from a nested Python list
tensor2d = torch.tensor([[1,2,3],
                         [4,5,6],
                         [7,8,9]])
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [87]:
# Create a 3D tensor '

tensor3d = torch.tensor([[[1,2],
                          [3,4]],
                          [[5,6],
                           [7,8]]])
tensor3d

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

## Tensor Data Types 

above we made tensors using python integers . In this case we have a default 64-bit data type. Data type can be found with the .dtype attribute of an integer. 

In [88]:
import torch
tensor1d = torch.tensor([6,7,6,7])
tensor1d.dtype


torch.int64

if we make tensors using python floats, PyTorch creats tensors with a 32-bit data type automatically

In [89]:
floatvec = torch.tensor([1.0, 2.0, 3.0])
floatvec.dtype

# uses a 32 bit float in order to offer precision while also taking up less memory than a 64 bit float

torch.float32

u can change the data type using the .to method

In [90]:
floatvec = tensor1d.to(torch.float32)
floatvec.dtype

torch.float32

## Essential Tensor Operations
---
There are many operations and commands in Pytorch, so learning all of them is uneccessary for me rn. 


In [91]:
tensor2d = torch.tensor([[1,2,3],[4,5,6]]) #torch.tensor() creates new tensors from data (like a list or nested list)
tensor2d

tensor([[1, 2, 3],
        [4, 5, 6]])

In [92]:
# the .shape attribute returns a tuple of the dimensions of a tensor
tensor2d.shape

torch.Size([2, 3])

In [93]:
# .reshape() and .view() allow us to reshape an input tensor to a defined shape
reshaped_tensor2d = tensor2d.reshape(3,2)
reshaped_tensor2d

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [94]:
# .T transposes a tensor (switches the dimensions)
reshaped_tensor2d.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [95]:
# .matmul() performs matrix multiplication between two tensors
tensor1 = torch.tensor([[1,2],
                        [3,4]])
tensor2 = torch.tensor([[5,6],
                        [7,8]])
torch.matmul(tensor1, tensor2)

tensor([[19, 22],
        [43, 50]])

In [96]:
#you can also use an alt way
tensor1 @ tensor2
#and another
tensor1.matmul(tensor2)

tensor([[19, 22],
        [43, 50]])

## Seeing models as computation graphs
--- 
- we covered Pytorch's tensor library but now we need to look into pytorch's automatic differentiation system 
- the module base class makes it easier to train models. 
- it allows us to encapsulate layers and operations and keep track of the model’s parameters

- computational graphs let us vizualize math concepts, in deep learning a computation graphn lets us veiw the math needed to output a neural network
- we need the calculations to compute the gradients for backpropogation which is the primary training algorithm for neural networks

In [97]:
import torch.nn.functional as F

y = torch.tensor([1.0]) # true label
x1 = torch.tensor([1.1]) # input feature
w1 = torch.tensor([2.2]) # weight
b = torch.tensor([0.0]) # bias

z = x1 * w1 + b # net input 
a = torch.sigmoid(z) # activation function
loss = F.binary_cross_entropy(a, y) # calculate the loss
print(loss)


tensor(0.0852)


The point of this logistic regression classifier isnt to implement it but more so help us understand how we can think of a sequance of computations as a computation graph

- pytorch builds compuation graphs in the background and we can use this to calculate the gradient of a loss function that follows the weight and bias models to train the model. 

## Automatic differentiation 
---
- gradients are required in training nn with backpropogation
- the chain rule is important as it is how nn calculate their errors within each layer and passes the error backward (backpropogation) to correct said errors 
- partial derivatives "freeze" variables and tweak one at the time to create a more structured tuning. (cake idea w/ deliciousness)
- "When PyTorch wants to update $w_1$, it uses a partial derivative ($\frac{\partial L}{\partial w_1}$). It asks: "If I hold the bias $b$ completely still, how much will tweaking $w_1$ reduce my error?"By calculating the partial derivative for $w_1$ and $b$ separately, PyTorch knows exactly how much to turn each individual knob to make the AI smarter."
- gradients are vectors that contain all the partial derivatives of a functoon with muliple variables as inputs. 

- intuitively, the chain rule is used to compute the loss function of a model's parameters in a cg. Loss function works as a tool for mesuring a models's performance

- the autograd engine creates a cg in the background. when we call the grad function, we compute the gradient of loss to the models parameter weight (w1). 



In [98]:
import torch
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])
x1 = torch.tensor([1.1]) 
w1 = torch.tensor([2.2], requires_grad=True) # set requires_grad to True to compute gradients
b = torch.tensor([0.0], requires_grad=True) # set requires_grad to True to compute gradients

z = x1 * w1 + b
a = torch.sigmoid(z)

loss = F.binary_cross_entropy(a, y)

grad_L_w1 = grad(loss,w1, retain_graph=True) # compute the gradient of the loss with respect to weight
grad_L_b = grad(loss,b, retain_graph=True) # compute the gradient of the loss with respect to bias

grad_L_w1, grad_L_b

((tensor([-0.0898]),), (tensor([-0.0817]),))

- the retain_graph function is used so the cg stays inside of PyTorch's memory because it deletes the graph automatically by default
- this code shows how the grad function gets used manually. Using this is good or experimentation, debugging, and demonstrating concepts 
- however, pt offeres high-level tools to automate this. we can call .backward on the loss and pytorch will compute all of the gradients on the nodes in the graph and these gradients get stored in the tensors' .grad functions

In [99]:
loss.backward() # compute the gradients of the loss with respect to all tensors with requires_grad=True

w1.grad, b.grad # access the gradients of w1 and b

(tensor([-0.0898]), tensor([-0.0817]))

#### Key Idea 

Pt's autograd component takes care of the calculus of the matter in chains of tensor operations using the .backward method. 

## Implementing multilayer NN
---
- We just looked at Pt's tensor and autograd components, but we going to shift to how Pt is a library that implements Deep NN's 
- torch.nn.Module provides functionality as it lets us buld and train models and encapsulating the layers and operations to keep track of a model's parameters
- the _init_ constructor defines the networks layers and how they interact with da forward method. 
- the foward method descides how da data passes through the networks and forms a cg
- we don't need to implement the backward method ourselves in a nn but it is used to compute the loss function w/ respect to da models parameters



In [100]:
class NeuralNetwork(torch.nn.Module):
    def __init__(self, num_inputs, num_outputs): 
        super().__init__() # call the __init__ method of the parent class (torch.nn.Module)

        self.layers = torch.nn.Sequential(

            # First Layer
            torch.nn.Linear(num_inputs, 30), # first layer with num_inputs and 30 neurons
            torch.nn.ReLU(), # activation function

            # Second Layer
            torch.nn.Linear(30, 20), # second layer with 30 inputs and 20 neurons
            torch.nn.ReLU(), # activation function

            # Output layer
            torch.nn.Linear(20, num_outputs) # output layer with 20 inputs and num_outputs neurons
        )
    def forward(self, x): # define the forward pass of the network
        logits = self.layers(x) # pass the input through the layers
        return logits
    
model = NeuralNetwork(50, 3)
print(model)

NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=50, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=3, bias=True)
  )
)


The Sequential class we used wasn't required but it was useful cuz we wwanted to execute the layers in a specific order. \
After instantiating the self.layers = Sequential(...) in the _init_ we just have to call self.layers instead of each layer individually. 

In [101]:
num_params = sum(
    p.numel() for p in model.parameters() if p.requires_grad
)
print(f"The model has {num_params} trainable parameters")

The model has 2213 trainable parameters


any parameter that requires_grad=True is a trainable parameter and gets updated in training
- the torch.nn.Linear layers contain the trainable parameters. 
- each linear layer multiplies the input w/ the weight matrix and adds the bias vector  <-- this is ref to as feedforward or a fully conected layer. 

In [102]:
print(model.layers[0].weight) #this shows the weight matrix that is multiplied against the inputs 


Parameter containing:
tensor([[ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        [-0.0920, -0.0480,  0.0105,  ..., -0.0923,  0.1201,  0.0330],
        ...,
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509],
        [-0.1250,  0.0513,  0.0366,  ..., -0.1370,  0.1074, -0.0704]],
       requires_grad=True)


In [103]:
print(model.layers[0].weight.shape) #this shows the dimentions of the matrix since its so massive and doesn't get shown entirely

torch.Size([30, 50])


- you can do the same for the bias vector with model.layers[0].bias
- this 30x50 matrix holds the defult trainable entries for weight in torch.nn.Linear
- the numbers within the matrix usually differ because the model weights are initiallized randomly to break symetry in training. Otherwise, the nodes would just be doing the same operations over and over which won't allow them to learn the mappings from inputs to outputs. 

In [104]:
torch.manual_seed(123) #manual_seed allows the random number intialization to be reproducable, kinda like a minecraft seed

model = NeuralNetwork(50,3)
print(model.layers[0].weight)

Parameter containing:
tensor([[-0.0577,  0.0047, -0.0702,  ...,  0.0222,  0.1260,  0.0865],
        [ 0.0502,  0.0307,  0.0333,  ...,  0.0951,  0.1134, -0.0297],
        [ 0.1077, -0.1108,  0.0122,  ...,  0.0108, -0.1049, -0.1063],
        ...,
        [-0.0787,  0.1259,  0.0803,  ...,  0.1218,  0.1303, -0.1351],
        [ 0.1359,  0.0175, -0.0673,  ...,  0.0674,  0.0676,  0.1058],
        [ 0.0790,  0.1343, -0.0293,  ...,  0.0344, -0.0971, -0.0509]],
       requires_grad=True)


In [105]:
torch.manual_seed(123)

X = torch.rand((1,50)) # generates a random traing expample that should return 3 scores 
out = model(X) # runs a foward pass on the nn
print(out)

tensor([[-0.1262,  0.1080, -0.1792]], grad_fn=<AddmmBackward0>)


- these results are expected as they represent the 3 output nodes of the neural network
- the output tensor also includes the grad_fn value
- the grad_fn=<AddmmBackward0> shows that last used function to compute the variables in a cg 
- Add shows the addition for the bias vector 
- mm shows the matrix multiplication for the weight matrix operation
- Addmm stands for mm folled by an addition
- if we arent focused on training or backpropogation, making the cg is unneccessary and jst consumes more memory. 
- torch.no_grad() is a context manager thats telss Pt that it doesnt need to track the gradients and this saves hecka memory and computation power. 



In [106]:
with torch.no_grad():
    out = model(X)
print(out)

tensor([[-0.1262,  0.1080, -0.1792]])


In [107]:
with torch.no_grad():
    out = torch.softmax(model(X), dim=1) #softmax computes the class membership probabilities for predictions without using a nonlinear activation function. 
out

tensor([[0.3113, 0.3934, 0.2952]])

these values can be interpreted as class-membership probabilities that = 1. The values are roughly equal for random output, which is expected for a model w/o training. 
## Setting up efficient data loaders
- in this section we'll implement a dataset class that we will use to create a training and test dataset that will be used to create a data loader. 


#### Class Label Numbering 
Pt reqirues that a class label needs to start with 0 and that the largest class label value should not be greater that the # of output nodes - 1 (since index counting starts at 0). so, if we have class labels 0, 1, 2, 3, and 4, the nn would have 5 nodes.  

In [109]:
import torch
import torch.nn.functional as F
from torch.autograd import grad
from torch.utils.data import DataLoader, Dataset



X_train = torch.tensor([
     [-1.2, 3.1],
    [-0.9, 2.9],
    [-0.5, 2.6],
    [2.3, -1.1],
    [2.7, -1.5]
])

y_train = torch.tensor([0,0,0,1,1])   # These are the training Datasets

X_test= torch.tensor([
    [-0.8,2.8],
    [2.6,-1.6],
])

y_test = torch.tensor([0,1])  # These are the test Datasets

class ToyDataset(Dataset):
    def __init__(self, X, y): # _init_ is the constructor that sets up the attributes that we use in the other methods. This could be file paths, file objects, database connectors and more. This just assigns the variables to the attributes but they really just placeholders for the tensor objects for now. 
        self.features = X
        self.labels = y 

    def __getitem__(self, index):
        one_x = self.features[index]
        one_y = self.labels[index]
        return one_x, one_y # the _getitem_ function just returns one item from the data set using the index. the index is supposed to be provided by the data loader. 

    def __len__(self): 
        return self.labels.shape[0] # the _len_ method gets the length of the dataset. it just uses the .shape attribute to return the number of rows in an array. 
    
train_ds = ToyDataset(X_train, y_train)
test_ds = ToyDataset(X_test, y_test)

torch.manual_seed(123)

train_loader = DataLoader(
    dataset= train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0
)
test_ds = ToyDataset(X_test, y_test)

test_loader = DataLoader(
    dataset=test_ds,
    batch_size=2,
    shuffle=False,
    num_workers=0
)

for idx, (x,y) in enumerate(train_loader):
    print(f"Batch {idx+1}:",x,y) 

Batch 1: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])
Batch 2: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 3: tensor([[ 2.7000, -1.5000]]) tensor([1])


- the train_loader visits each training example exactly once. This is called training epoch. 
- if you run over the dataset a second time, the shuffling order would change. This is important because it ensures a nn doesn't get caught in repetitive cycles in training.
- As we can see, the batch size of 2, leaves a remainder batch with an odd amount of examples. This could disturb convergence during traing. to prevent use drop_last=True. 

In [ ]:

train_loader = DataLoader(
    dataset= train_ds,
    batch_size=2,
    shuffle=True,
    num_workers=0,
    drop_last=True
)
for idx, (x,y) in enumerate(train_loader):
    print(f"Batch {idx+1}:",x,y)

Batch 1: tensor([[-1.2000,  3.1000],
        [-0.5000,  2.6000]]) tensor([0, 0])
Batch 2: tensor([[ 2.3000, -1.1000],
        [-0.9000,  2.9000]]) tensor([1, 0])


The num_workers=() is very crucial for parallelizing data loading and procesing. When it is set to 0 the data loading is done in the main process instead of seperate worker processes. This is a problem for larger datasets because the GPU would sit idle while the CPU is finishing tasks so its inefficient.
\. 
When the num_workers is set to greater than 0, multiple worker processes are used to load data in parallel which fees that main process to focus on train the model. 
\.
With small datasets its not necessary to set the num_workers >0 and could lead to issues so its important to understand the trade off and make a calculated decision in setting the parameter. num_workers=4 is usually good for real world dataset usage. 

## A typical training loop. 
- putting everything together to train a nn on the previously mentioned ToyDataset


In [112]:

import torch.nn.functional as F


torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)
optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):
    
    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        logits = model(features)

        loss = F.cross_entropy(logits, labels) # this da loss function

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### Logging
        print(f"Epoch: {epoch+1:03d}/{len(train_loader):03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")
model.eval()
#option model evaluation

Epoch: 001/003 | Batch 000/003 | Train/Val Loss: 0.75
Epoch: 001/003 | Batch 001/003 | Train/Val Loss: 0.65
Epoch: 001/003 | Batch 002/003 | Train/Val Loss: 0.42
Epoch: 002/003 | Batch 000/003 | Train/Val Loss: 0.05
Epoch: 002/003 | Batch 001/003 | Train/Val Loss: 0.13
Epoch: 002/003 | Batch 002/003 | Train/Val Loss: 0.00
Epoch: 003/003 | Batch 000/003 | Train/Val Loss: 0.01
Epoch: 003/003 | Batch 001/003 | Train/Val Loss: 0.00
Epoch: 003/003 | Batch 002/003 | Train/Val Loss: 0.02


NeuralNetwork(
  (layers): Sequential(
    (0): Linear(in_features=2, out_features=30, bias=True)
    (1): ReLU()
    (2): Linear(in_features=30, out_features=20, bias=True)
    (3): ReLU()
    (4): Linear(in_features=20, out_features=2, bias=True)
  )
)

- two inputs and two outputs for two input features are two class labels to predict.
-  we used the stochastic gradient descent (SDG) optimizer with a learning rate (lr) of 0.5. The lr is a tunabloe hyperparameter which we want to choose for the loss to converge after a specific number of epochs. The number of epochs is another hyperparameter. 
- in practice we use a validation dataset in order to find the most optimal hyperparameter settings. We use the validation data set like a test dataset but multiple times to tweak the models settings. 
- model.train() and model.eval() are settings that put are model in training and evaluation modes This is important for models that vary differetly in different modes, but its redundant in ours above. However, it should still be included because we dont want unexpected behaviors when we change the model or reuse the code to train another model. 
- cross_entropy is the loss function which applies the softmax function, then the loss.backward() calculates the grads, then the optimizer.step() method updates the models parameters to minimize the loss. 
- inside of the SDG optimizer this means multiplying the gradients w/ the lr and adding the scaled negative to the gradients parameters 
- after training the model we can use it to make predictions

In [113]:
model.eval()

with torch.no_grad():
    outputs = model(X_train)

print(outputs) #this shows the predictions for the X_train dataset



tensor([[ 2.9320, -4.2563],
        [ 2.6045, -3.8389],
        [ 2.1484, -3.2514],
        [-2.1461,  2.1496],
        [-2.5004,  2.5210]])


In [ ]:
torch.set_printoptions(sci_mode=False)
probas = torch.softmax(outputs, dim=1)
print(probas) # gets the class membership probabilities 


tensor([[0.9992, 0.0008],
        [0.9984, 0.0016],
        [0.9955, 0.0045],
        [0.0134, 0.9866],
        [0.0066, 0.9934]])


In [115]:
#the probabilities in the graph above show the 0 and 1 classes left collum = percent that its in 0 class and right is for 1 
predictions = torch.argmax(probas, dim=1)
print(predictions) 

tensor([0, 0, 0, 1, 1])


In [116]:
# you dont necessarily need the softmac probabilities to obtain the class labels 
predictions = torch.argmax(outputs, dim=1)
print(predictions)


tensor([0, 0, 0, 1, 1])


In [117]:
predictions == y_train
#this checks the predections back to the dataset

tensor([True, True, True, True, True])

In [118]:
torch.sum(predictions == y_train)
#counts sum of correct predictions

tensor(5)

In [119]:
def compute_accuracy(model, dataloader):

    model.eval()
    correct = 0.0
    total_examples = 0 

    for idx, (features, labels) in enumerate(dataloader):

        with torch.no_grad():
            logits = model(features)
        
        predictions = torch.argmax(logits, dim=1)
        compare = labels == predictions
        correct += torch.sum(compare)
        total_examples += len(compare)

    return (correct / total_examples).item()
# this function iterates over a data loader to compute the number and fraction of correct predictions. Memory limitations make this the general method because it makes sure the model receives the same size as the batch size it saw in training. 

In [120]:
compute_accuracy(model, train_loader)

1.0

In [121]:
compute_accuracy(model, test_loader)

1.0

## Saving and Loading models 
We just learned how to train a model now how can we save it. 

In [122]:
torch.save(model.state_dict(), "model.pth")
#this saves the model to the disk by creating a python dictionary object that maps each layer in the model to its trainable parameters. 


In [ ]:
model = NeuralNetwork(2, 2) # needs to match the original model exactly
model.load_state_dict(torch.load("model.pth", weights_only=True))
#This restores the model from the disk 
#torch.load() just reads the file

<All keys matched successfully>

In [ ]:
torch.manual_seed(123)
model = NeuralNetwork(num_inputs=2, num_outputs=2)

# New: Define a device variable that defaults to a GPU.
device = torch.device("cuda")
# New: Transfer the model onto the GPU.
model.to(device)

optimizer = torch.optim.SGD(model.parameters(), lr=0.5)

num_epochs = 3

for epoch in range(num_epochs):

    model.train()
    for batch_idx, (features, labels) in enumerate(train_loader):

        # New: Transfer the data onto the GPU.
        features, labels = features.to(device), labels.to(device)    #C
        logits = model(features)
        loss = F.cross_entropy(logits, labels) # Loss function

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        ### LOGGING
        print(f"Epoch: {epoch+1:03d}/{num_epochs:03d}"
              f" | Batch {batch_idx:03d}/{len(train_loader):03d}"
              f" | Train/Val Loss: {loss:.2f}")

    model.eval()
    # Optional model evaluation

- the three lines of code here allow for the model to be excecuted on a single GPU
- device = torch.device("cuda" if torch.cuda.is_available() else "cpu") can also be used to have the model run on cpu if gpu isn't available. This is usually the best method when sharing code. 
- There's not a significant elevation in speed in this example because of the memory transfer cost from CPU to GPU however for training deep nn and LLMS it is way more efficient 

In [1]:
from transformers import pipeline

# Example: text generation with GPT-2
generator = pipeline("text-generation", model="gpt2")
result = generator("Once upon a time", max_length=50)
print(result)

c:\Users\sjcap\OneDrive\infleqtion_summer\venv\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\sjcap\OneDrive\infleqtion_summer\venv\Lib\site-packages\huggingface_hub\file_download.py:138: UserWarning: `huggingface_hub` cache-system uses symlinks by default to efficiently store duplicated files but your machine does not support them in C:\Users\sjcap\.cache\huggingface\hub\models--gpt2. Caching files will still work but in a degraded version that might require more space on your disk. This warning can be disabled by setting the `HF_HUB_DISABLE_SYMLINKS_WARNING` environment variable. For more details, see https://huggingface.co/docs/huggingface_hub/how-to-cache#limitations.
To support symlinks on Windows, you either need to activate Developer Mode or to run Python as an administrator. In order to activate 

[{'generated_text': 'Once upon a time, he was a member of the church of St. Gregory Nazianzen, a small and highly cultured organization. He was the first to call for the return of the gospel to the Church. In his writings, he has declared that the restoration of the gospel would be accomplished by a "new and faithful Church, of which the faith of the whole Church will be the chief object." He is referring to the Church which would have to be saved and of which all of the saints would have to be saved. For the Church would have to be destroyed to prevent the restoration of the gospel.\n\nIn his apostolic letter, the Church "will be saved," after which he spoke of the power of the Holy Spirit "to bring out all the things which are not in darkness, or in the darkness, and to bring out all the things which are in the light, and to bring out all the things which are in the darkness."\n\nThe Apostle Paul\'s "new and faithful Church" is a "new and faithful Church." It is a church of the faith

In [ ]:
import os
os.environ['HF_TOKEN'] = 'my love is mine all mine my love is mine all mineeee'

from openai import OpenAI

client = OpenAI(
    base_url="https://router.huggingface.co/v1",
    api_key=os.environ["HF_TOKEN"],
)

completion = client.chat.completions.create(
    model="meta-llama/Llama-3.1-8B-Instruct",
    messages=[
        {
            "role": "user",
            "content": "Generate a quantum ciruit in Cirq that simulates a bell state."
        }
    ],
)

print(completion.choices[0].message)

ChatCompletionMessage(content='# Quantum Circuit for Bell State in Cirq\n\nHere\'s a Python code example using Cirq to create a quantum circuit that generates a Bell state (specifically the |Φ⁺⟩ state):\n\n```python\nimport cirq\n\n# Create a quantum circuit with 2 qubits\nqubits = cirq.LineQubit.range(2)  # qubits 0 and 1\ncircuit = cirq.Circuit()\n\n# Add gates to create the Bell state |Φ⁺⟩ = (|00⟩ + |11⟩)/√2\ncircuit.append([\n    # Apply Hadamard gate to qubit 0\n    cirq.H(qubits[0]),\n\n    # Apply CNOT gate with qubit 0 as control and qubit 1 as target\n    cirq.CNOT(qubits[0], qubits[1])\n])\n\n# Print the circuit\nprint("Circuit to create Bell state |Φ⁺⟩:")\nprint(circuit)\n\n# Visualize the circuit\nprint("\\nCircuit diagram:")\nprint(circuit.to_text_diagram())\n```\n\n## Explanation:\n\n1. **Qubits**: We create two qubits (qubit 0 and qubit 1) using `cirq.LineQubit.range(2)`.\n\n2. **Hadamard Gate**: The Hadamard gate (H) on qubit 0 puts it in a superposition state:\n   - |0

ChatCompletionMessage(content='# Quantum Circuit for Bell State in Cirq\n\nHere\'s a Python code example using Cirq to create a quantum circuit that generates a Bell state (specifically the |Φ⁺⟩ state):\n\n```python\nimport cirq\n\n# Create a quantum circuit with 2 qubits\nqubits = cirq.LineQubit.range(2)  # qubits 0 and 1\ncircuit = cirq.Circuit()\n\n# Add gates to create the Bell state |Φ⁺⟩ = (|00⟩ + |11⟩)/√2\ncircuit.append([\n    # Apply Hadamard gate to the first qubit\n    cirq.H(qubits[0]),\n\n    # Apply CNOT gate with first qubit as control and second as target\n    cirq.CNOT(qubits[0], qubits[1])\n])\n\n# Print the circuit\nprint("Circuit to create Bell state |Φ⁺⟩:")\nprint(circuit)\n\n# Visualize the circuit\nprint("\\nCircuit diagram:")\nprint(circuit.to_text_diagram())\n```\n\n## Explanation:\n\n1. **Qubits**: We create two qubits (qubit 0 and qubit 1) using `cirq.LineQubit.range(2)`.\n\n2. **Hadamard Gate**: The Hadamard gate (H) is applied to the first qubit, putting it in a superposition state:\n   ```\n   |0⟩ → (|0⟩ + |1⟩)/√2\n   ```\n\n3. **CNOT Gate**: The controlled-NOT gate (CNOT) is applied with the first qubit as control and the second qubit as target. This entangles the two qubits, creating the Bell state:\n   ```\n   (|0⟩ + |1⟩)|0⟩ → |00⟩ + |11⟩\n   ```\n\n4. **Result**: The final state is the Bell state |Φ⁺⟩ = (|00⟩ + |11⟩)/√2.\n\n## Output:\n\nWhen you run this code, you\'ll see:\n\n```\nCircuit to create Bell state |Φ⁺⟩:\n(0, 0): ───H───@───\n                │\n(0, 1): ───────X───\n\nCircuit diagram:\n(0, 0): ───H───@───\n                │\n(0, 1): ───────X───\n```\n\nThis shows the Hadamard gate followed by the CNOT gate that creates the entangled Bell state.', refusal=None, role='assistant', annotations=None, audio=None, function_call=None, tool_calls=[], reasoning=None)


In [3]:
# how can we convert model output to cirq circuit most effectively - Palash
import cirq
circuit = cirq.Circuit()
q0,q1 = cirq.LineQubit.range(2)
circuit += cirq.H(q0)
circuit += cirq.CX(q0,q1)
print(circuit)

0: ───H───@───
          │
1: ───────X───


In [5]:
cirq.final_state_vector(circuit)

array([0.70710677+0.j, 0.        +0.j, 0.        +0.j, 0.70710677+0.j],
      dtype=complex64)

In [8]:
for op in circuit.all_operations():
    print(op)

H(q(0))
CNOT(q(0), q(1))


In [9]:
cirq.num_qubits(circuit)

2

In [ ]:
def validation() <-- #build basic validation system 