In [ ]:
import numpy as np

#creating an array
a = np.array([1, 2, 3, 4, 5])

b = np.array([[0,1,2],[1,0,3]])

a.ndim # Get the number of dimensions of the array
b.shape # Get the shape of the array
a.dtype # Get the data type of the array
a.itemsize # Get the size of each element in bytes
#Get total size
a.nbytes # Get the total size of the array in bytes

#Accessing/Changing specific elements, rows, columns, etc.
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

# Get a specific element [r,c]

print(a[1,5]) # 13
print(a[1,-2]) # 13

#Get a specific row

print(a[0,:]) # [1 2 3 4 5 6 7]

#get a specific column

print(a[:,2]) # [3 10]

#Getting a little more fancy[startindex:endindex:stepsize]
print(a[0,1:6:2]) # [2 4 6]

a[1,5] = 20
print(a) # changes 13 to 20

a[:,2] = [1,2]
print(a) # makes third column 1 and 2

#3D example
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)
b[1,1,1] # 8
b[0,1,0] # 3
# replace 
b[ :,1, :] = [[9,9],[9,9]] #make sure they the same size arrays
print(b)

#Different types of arrays
#all 0s matrix
zeros = np.zeros((2,3))
print(zeros)
#all 1s matrix
ones = np.ones((4,2,2))
print(ones)


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
13
13
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
[[[1 2]
  [9 9]]

 [[5 6]
  [9 9]]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


##Background

Numpy is a multidimensional array library for Python. It provides a powerful and efficient way to work with arrays and matrices. Numpy arrays are more efficient than Python lists because they are stored in contiguous memory locations, which allows for faster access and manipulation.

An array is basically just a line of boxes that hold data. It is a data structure that can hold multiple values of the same type.

Lists are slow and numpy is fast because numpy uses fixed type. Our computers see 5 in bianary which is 1 byte but numpy uses int32 which makes it 4 bytes. This allows numpy to optimize memory usage and speed up operations. lists hold many different types of data which makes it way slower using almos 30 bytes. 

Numpy = no type checking like lists

Numpy also uses contiguous memory sp all the data is right next to eachout whereas Lists are more sporatic. This lets our SIMD Vector Processing to perform computing to all values at the same time Numpy uses our cache more.

Numpy has more features that Lists

Cant multipy list but numpy arrays can be multiplied

There are hecka applications for numpy in most Mathamatics

Plotting with Matplotlib 

Backend (Pandas, Connect 4, and Digital Photography)

Super important for machine learning with Tensors. 